sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_adsel/
- coverage run uw_adsel/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_adsel/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_adsel/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
  password:
    secure: gxzX1/Q6dMlI/hDuAKOULGJhqRGnVsGqsp1PJwNasIFey20DiwqtGQQQvRNhh0c+AfL8P0d09F82kunZNw2A0+eFDfckOlSPLymZ0vhq+PONIsrmNajyi3zaCLQil0QRQnAuyfPVO5milBUe94C3alFJaMXeFaKqJWSDMx6GBAqOGeUGf3e3Rwy9qTGpq34PdZ3YV5+kdPSA6sn43ZiJH4Js8PPNsoLAxzFJCxHUjfg6Z885vh7E64z/omDqVuWJzueEuRtgIGrpPs/i56ViKCJltKXGHw5eUfhwJpDVDhZwPEoqfj1gL7smc2MrReIaK7L/OwcnoJ5jcd1uj9bkTxqE+l/YunCmIIIL6Y2b9Sy8H+Yt5f/+97k3WJdvNqRGAVgdVu8OBifUGdMp5RHdpzsYk8pvlbyEViSI9bQBNh0Kn9oIlnj9TT/Z4z2gW5YLjQjzlEOD9WPSKMlhXR6Mtlo/ysziSa5YMn870Pj85aNGDg8raFr6g30EoDITeQY750xBn1G1enA30Y9izowF9dD9Cuf8xO1Q5qkl9PCAWaN+3wRoFE63enja+meqOns9GsGrkKGmlBEtSDioH4vPsegD5yAA8/6hfxCYNv0hv6o3DrLq0n9/Yo05epN/YCXTy6gp/YT8Sog4dED/2RNQ0EZiCIBHcAP1u6EzjRLXT2o=
