sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_adsel/
- coverage run uw_adsel/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_adsel/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_adsel/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
  password:
      secure: "i8ISbTyF8+tOSFKElu+s7mueHE2ogIYblB/acdXNRJUFmghvxjgH6dB/0oL2dCM+cp3l1TMlu7IWsZS61LAznci3QWKBEWsYr8rMpRJz0+Nwgd+Avg662Z+nilLXuBRQKhKZ9WS0x1ReEP5Kgfta+OtS+9kUqqkGX1TJi3gamafqhGFBkaie9PhsYMd5bR/DmknIBeqr6KI5HajSh0I52ilx3UmbMgReiLafqPDMIUrOCsP2lc/Xg1gXzginv2hP3nXAum0t1MmXBYI4ChVQohTb1mehyrUeHwS4PLtrJRz7HKpGtm23Z2Su5FCIFkDbV0/F7wvQQlBs33Por/R6Erxj7Aoi57rhRuLmvTuBN1MzHVoIsqss6fuCdUhTh+2QZYg66XBPOSyFjY3xSNVre/xvj63j0CcoOj5TWxKLYKkZbS+x/Q/5c+ePjSOFEmuQgT6327NXAmtuIbAciynBJ1DX59fTWLmArxxmnkh2/bJYhiPCvRnQy6/xqHJM9pz8VDgw0Xp9vBRKxk1kP5SoC3bBrVgS6FIr426at12hFeF/IfJ8hMzPFChj2KMJPHuA8y9+S6F5IiaGTTjO+WXBkhh7q4mapxXzaiENi9z17XCfQmiEB0XCZyRzjrTfoGw5uB2e38r3HOe4TvF52hEbjRynYb6r41DFY4cZQYum2es="